<?php
/** Phase 6 SYNTHETIC permanent-provider/storage/scheduler assertions; no real vendor calls. */
require rtrim(getenv('GRW_WP_ROOT'),'/').'/wp-load.php';
use Webifya\GRW\{Locations,Reviews,Widgets,Sync,Sources,PermanentReviewProvider,Renderer,Installer,Analytics,Cache,Admin};
global $wpdb;$n=0;$ids=[];$widgets=[];$calls=0;$mode='normal';$permission=true;$deletePermission=true;$text='SYNTHETIC Phase6 original content';$settings=get_option('grw_settings');$grants=get_option('grw_license_grants',false);
function v6($ok,$label){global $n;if(!$ok)throw new RuntimeException($label);echo "PASS: $label\n";$n++;}
$provider=new class implements PermanentReviewProvider {
 public function label():string{return 'SYNTHETIC Phase6 permitted provider';}
 public function supports_sync():bool{return true;}
 public function policy():array{global $permission,$deletePermission;return ['permanent_storage'=>$permission,'public_display'=>true,'license_reference'=>'https://example.org/phase6-contract','deletions'=>$deletePermission];}
 public function fetch(array $location,?string $cursor){global $calls,$mode,$text;$calls++;if($mode==='auth')return new WP_Error('provider_auth','RAW_SECRET_NEVER_PUBLISH');if($mode==='remove')return ['reviews'=>[],'removed_ids'=>['stable-1'],'cursor'=>null];if($mode==='bad_delete')return ['reviews'=>[],'removed_ids'=>[['nested']],'cursor'=>null];return ['reviews'=>[['external_id'=>'stable-1','reviewer'=>'SYNTHETIC Phase6 reviewer','rating'=>5,'content'=>$text,'review_date'=>'2024-01-01','source_name'=>'SYNTHETIC licensed source','source_url'=>'https://example.org/reviews','permalink'=>'https://example.org/review/1','response'=>'SYNTHETIC business response']], 'cursor'=>null];}
};
$filter=fn($a)=>array_merge($a,['fixture6'=>$provider]);add_filter('grw_source_adapters',$filter);
$d=Widgets::defaults();v6($d['limit']===100&&$d['sort']==='latest','new widget defaults to 100 newest reviews');v6($d['autoplay']&&$d['interval']===5000&&$d['loop']&&$d['pause_hover'],'default autoplay five seconds looping hover pause');v6($d['desktop']===3&&$d['tablet']===2&&$d['mobile']===1&&$d['swipe'],'default responsive cards and swipe');v6($d['analytics']&&!$d['show_map'],'widget analytics enabled and new map UI disabled');
delete_option('grw_settings');Installer::activate();v6(get_option('grw_settings')['analytics']===true&&get_option('grw_settings')['consent_required']===true,'fresh analytics enabled with explicit consent');update_option('grw_settings',['analytics'=>false,'consent_required'=>false,'retention'=>180,'delete_data'=>false]);Installer::activate();v6(get_option('grw_settings')['analytics']===false&&get_option('grw_settings')['retention']===180,'migration preserves saved analytics opt-out and retention');update_option('grw_settings',$settings);
$l=Locations::save(['name'=>'SYNTHETIC Phase6 business','provider'=>'fixture6','place_id'=>'ChIJphase6']);$ids[]=$l;$loc=Locations::get($l);v6(json_decode($loc['data'],true)['frequency']===259200,'new location frequency is 72 hours');v6((int)$loc['next_sync']===0&&!Sources::connection($loc)['connected'],'saving source does not schedule or validate collection');
$r=Sync::run($l);$loc=Locations::get($l);v6($r['added']===1&&$r['retrieved']===1&&$r['complete'],'initial permitted fixture collection stored');v6((int)$loc['next_sync']>=time()+259190&&(int)$loc['next_sync']<=time()+259210,'successful initial collection schedules 72 hours');v6(Sources::connection($loc)['status']==='Connected — Every 3 days','three-day connection status accurately labeled');$beforeCalls=$calls;do_action('grw_tick');v6($calls===$beforeCalls,'cron does not rerun before due time');
$row=Reviews::query(['admin'=>true,'locations'=>[$l]])[0];v6($row['provider_id']==='fixture6'&&$row['external_id']==='stable-1'&&$row['source_binding']===Sources::binding($loc),'stored provider business stable ID provenance');v6($row['license_reference']==='https://example.org/phase6-contract'&&!empty($row['synced_at']),'license and last synchronization timestamp recorded');v6($row['response']==='SYNTHETIC business response'&&$row['permalink']==='https://example.org/review/1','response and original review link retained');
$wpdb->update($wpdb->prefix.'grw_reviews',['synced_at'=>'2000-01-01 00:00:00'],['id'=>$row['id']]);$r=Sync::run($l);$same=Reviews::query(['admin'=>true,'locations'=>[$l]])[0];v6($r['unchanged']===1&&$r['duplicates']===1&&$same['id']===$row['id'],'manual repeated sync skips duplicates and preserves identity');v6($same['synced_at']!=='2000-01-01 00:00:00'&&$same['updated_at']===$row['updated_at'],'unchanged sync refreshes timestamp without pretending content changed');
$w=Widgets::save(['name'=>'SYNTHETIC local Phase6 widget','config'=>['locations'=>[$l]]]);$widgets[]=$w;$beforeCalls=$calls;$html=do_shortcode('[google_reviews_widget id="'.$w.'"]');v6(str_contains($html,'SYNTHETIC Phase6 reviewer')&&$calls===$beforeCalls,'local shortcode renders saved data without provider calls');v6(str_contains($html,'https://example.org/review/1')&&str_contains($html,'SYNTHETIC licensed source'),'local cards preserve source and review attribution');$text='SYNTHETIC changed original content';$r=Sync::run($l);v6($r['updated']===1&&Reviews::query(['admin'=>true,'locations'=>[$l]])[0]['id']===$row['id'],'changed content updates stable record');v6(str_contains(Renderer::render($w),$text),'changed sync invalidates widget cache');
foreach([86400,259200,432000,604800,0] as $frequency){Locations::save(['id'=>$l,'frequency'=>$frequency]);$saved=Locations::get($l);v6(json_decode($saved['data'],true)['frequency']===$frequency&&Sources::connection($saved)['connected']&&($frequency?(int)$saved['next_sync']>=time()+$frequency-10:(int)$saved['next_sync']===0),'schedule choice '.$frequency.' preserves validated collection');}
Locations::save(['id'=>$l,'frequency'=>259200]);$beforeCalls=$calls;$wpdb->update($wpdb->prefix.'grw_locations',['next_sync'=>time()-1],['id'=>$l]);do_action('grw_tick');v6($calls===$beforeCalls+1&&(int)Locations::get($l)['next_sync']>time()+259000,'actual cron hook processes due 72-hour fixture');$beforeCalls=$calls;do_action('grw_tick');v6($calls===$beforeCalls,'duplicate cron tick does not rerun completed job');add_option('grw_lock_'.$l,time(),'','no');v6(is_wp_error(Sync::run($l))&&$calls===$beforeCalls,'per-location lock blocks concurrent download');delete_option('grw_lock_'.$l);
$lastSuccess=Locations::get($l)['last_success'];$mode='auth';$err=Sync::run($l);$failed=Locations::get($l);v6(is_wp_error($err)&&!str_contains($err->get_error_message(),'RAW_SECRET'),'failed provider is not reported as successful');v6($failed['last_success']===$lastSuccess,'provider failure retains last successful retrieval');v6((int)$failed['next_sync']>=time()+890&&(int)$failed['next_sync']<=time()+910,'temporary failure retries with bounded first backoff');v6(str_contains(Renderer::render($w),$text),'prior permitted local collection survives provider outage');$mode='normal';Sync::run($l);v6(!get_option('grw_sync_error_'.$l)&&Sources::connection(Locations::get($l))['connected'],'successful retry restores safe connection status');
$other=Locations::save(['name'=>'SYNTHETIC separate Phase6 business','provider'=>'fixture6','place_id'=>'ChIJphase6other']);$ids[]=$other;Sync::run($other);v6(count(Reviews::query(['admin'=>true,'locations'=>[$other]]))===1&&count(Reviews::query(['admin'=>true,'locations'=>[$l]]))===1,'same external ID stays separate by business');
$mode='bad_delete';v6(is_wp_error(Sync::run($l))&&count(Reviews::query(['admin'=>true,'locations'=>[$l]]))===1,'malformed deletion signal does not delete rows');$mode='remove';$deletePermission=false;v6(is_wp_error(Sync::run($l))&&count(Reviews::query(['admin'=>true,'locations'=>[$l]]))===1,'provider deletion requires explicit contract capability');$deletePermission=true;$r=Sync::run($l);v6($r['removed']===1&&$r['expired']===0&&count(Reviews::query(['admin'=>true,'locations'=>[$other]]))===1,'explicit provider removal deletes only matching collection and reports count');v6(Renderer::render($w)===''&&!Sources::connection(Locations::get($l))['connected'],'empty removed collection invalidates cache and connected status');
$mode='normal';$permission=false;$beforeCalls=$calls;v6(is_wp_error(Sync::run($l))&&$calls===$beforeCalls,'temporary or revoked storage grant rejected before retrieval');$request=new WP_REST_Request('POST');$request->set_param('action','test_connection');$request->set_param('id',$l);v6(is_wp_error(Admin::handle('tools',$request)),'connection test cannot bypass storage permission');$permission=true;$response=Admin::handle('tools',$request);v6($response['success']&&$response['accessible_count']===1,'connection validation uses complete safe stored sync');
$fixture=Locations::save(['name'=>'SYNTHETIC local volume fixture','provider'=>'import']);$ids[]=$fixture;$rows=[];for($i=0;$i<120;$i++)$rows[]=['external_id'=>'ordered-'.$i,'reviewer'=>'SYNTHETIC ordered '.$i,'content'=>'SYNTHETIC volume content','rating'=>5,'review_date'=>'2024-'.sprintf('%02d',1+intdiv($i,28)).'-'.sprintf('%02d',1+$i%28)];Reviews::import($rows,$fixture);$volume=Widgets::save(['name'=>'SYNTHETIC volume widget','config'=>['source'=>'','locations'=>[$fixture]]]);$widgets[]=$volume;$full=Renderer::render($volume);v6(substr_count($full,'<article')===100&&str_contains(substr($full,strpos($full,'<article'),1200),'SYNTHETIC ordered 119'),'local default renders 100 newest records');v6(substr_count(do_shortcode('[google_reviews_widget id="'.$volume.'" limit="20"]'),'<article')===20,'shortcode limit override renders 20 saved records');v6(count(Reviews::query(['admin'=>true,'locations'=>[$fixture]],2,50))===50,'local queries paginate without loading entire collection');
$beforeAnalytics=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}grw_analytics",ARRAY_A);Sync::run($l);v6($beforeAnalytics===$wpdb->get_results("SELECT * FROM {$wpdb->prefix}grw_analytics",ARRAY_A)&&(int)Widgets::get($w)['id']===$w,'synchronization preserves analytics and widget relationships');
remove_filter('grw_source_adapters',$filter);foreach($widgets as $x)$wpdb->delete($wpdb->prefix.'grw_widgets',['id'=>$x]);foreach($ids as $x){foreach(['reviews','logs'] as $t)$wpdb->delete($wpdb->prefix.'grw_'.$t,['location_id'=>$x]);$wpdb->delete($wpdb->prefix.'grw_locations',['id'=>$x]);foreach(['grw_cursor_','grw_sync_progress_','grw_sync_counts_','grw_sync_error_'] as $prefix)delete_option($prefix.$x);}update_option('grw_settings',$settings);if($grants===false)delete_option('grw_license_grants');else update_option('grw_license_grants',$grants,false);Cache::invalidate();
echo "$n Phase 6 synthetic assertions passed; live retrieval and a real 72-hour cycle NOT verified.\n";
