<?php
/** Phase 7 synthetic software checks only; no real Google retrieval. */
require rtrim(getenv('GRW_WP_ROOT'),'/').'/wp-load.php';
use Webifya\GRW\{Security,Admin,Locations,Reviews,Widgets,Sources,Sync,Installer,Places,GoogleBusiness,PermanentReviewProvider,Renderer};
global $wpdb;$n=0;$ids=[];$widgets=[];$calls=0;$network=0;$fail=false;
function v7($ok,$label){global $n;if(!$ok)throw new RuntimeException($label);echo "PASS: $label\n";$n++;}
$block=function($pre,$args,$url){global $network;$network++;return new WP_Error('blocked','Synthetic test forbids external requests');};add_filter('pre_http_request',$block,1,3);
foreach(['ChIJphase7','https://www.google.com/maps?cid=123','https://www.google.com/maps/search/?api=1&query=Test&query_place_id=ChIJphase7','https://maps.app.goo.gl/fixture7'] as $input){$r=Security::identify($input);v7(!is_wp_error($r)&&!$r['verified']&&!$r['reviews_retrieved'],'local-only accepted identifier '.$input);}
v7(Security::identify('ChIJphase7')['place_id']==='ChIJphase7','Place ID parsed without business lookup');v7(Security::identify('https://www.google.com/maps?cid=123')['cid']==='123','CID parsed locally');
foreach(['http://www.google.com/maps?cid=123','https://evil.example/maps','https://www.google.com.evil.example/maps','https://127.0.0.1/maps','https://user:secret@www.google.com/maps','https://www.google.com:8443/maps','https://www.google.com/search?q=test','https://WWW.GOOGLE.COM/search?q=test','javascript:alert(1)','<script>alert(1)</script>',str_repeat('a',2049),''] as $input)v7(is_wp_error(Security::identify($input)),'reject unsafe or invalid identifier '.substr($input,0,40));
v7($network===0,'identifier validation issues zero HTTP requests');
$provider=new class implements PermanentReviewProvider{
 public function label():string{return 'SYNTHETIC Phase7 storage provider';}public function supports_sync():bool{return true;}
 public function policy():array{return ['permanent_storage'=>true,'public_display'=>true,'license_reference'=>'https://example.org/phase7-license'];}
 public function fetch(array $location,?string $cursor){global $calls,$fail;$calls++;if($fail)return new WP_Error('provider_network','DO_NOT_LEAK_PROVIDER_RESPONSE');return ['reviews'=>[['external_id'=>'stable7','reviewer'=>'SYNTHETIC Phase7 reviewer','rating'=>5,'content'=>'SYNTHETIC permitted fixture, not a Google review','review_date'=>'2024-01-01','source_name'=>'SYNTHETIC Phase7 provider']], 'cursor'=>null];}
};$filter=fn($a)=>array_merge($a,['fixture7'=>$provider]);add_filter('grw_source_adapters',$filter);
$l=Locations::save(['name'=>'SYNTHETIC Phase7 business','provider'=>'fixture7','place_id'=>'ChIJphase7']);$ids[]=$l;v7(!Sources::connection(Locations::get($l))['connected']&&(int)Locations::get($l)['next_sync']===0,'new permitted provider remains unvalidated and unscheduled');$r=Sync::run($l);v7($r['added']===1&&$r['complete'],'permitted fixture initial retrieval uses existing sync');v7((int)Locations::get($l)['next_sync']>=time()+259190,'validated fixture schedules 72 hours');$w=Widgets::save(['name'=>'SYNTHETIC Phase7 widget','config'=>['locations'=>[$l]]]);$widgets[]=$w;$before=$calls;v7(str_contains(Renderer::render($w,[],true),'SYNTHETIC Phase7 reviewer')&&$calls===$before,'local shortcode renders permitted review without fetching');$r=Sync::run($l);v7($r['added']===0&&$r['duplicates']===1,'repeat permitted fixture retrieval prevents duplicates');$fail=true;v7(is_wp_error(Sync::run($l)),'temporary provider failure is recorded');$c=Sources::connection(Locations::get($l));v7($c['connected']&&str_contains($c['status'],'requires attention'),'temporary failure keeps previously validated stored collection');v7(str_contains(Renderer::render($w,[],true),'SYNTHETIC Phase7 reviewer'),'temporary failure preserves permitted carousel content');v7(!str_contains(wp_json_encode($c),'DO_NOT_LEAK'),'safe status excludes raw provider errors');
$rid=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}grw_reviews WHERE location_id=%d",$l));wp_set_current_user(get_user_by('login','grwtest')->ID);$req=new WP_REST_Request('GET','/grw/v1/state');$state=Admin::handle('state',$req);$loc=array_values(array_filter($state['locations'],fn($a)=>(int)$a['id']===$l))[0];v7($loc['saved_count']===1&&$loc['display_count']===1,'saved and locally displayable counts separate');Reviews::moderate($rid,'hide');$state=Admin::handle('state',$req);$loc=array_values(array_filter($state['locations'],fn($a)=>(int)$a['id']===$l))[0];v7($loc['saved_count']===1&&$loc['display_count']===0,'hidden review remains stored but not displayable');Reviews::moderate($rid,'show');
$oldPlaces=get_option('grw_places_private',false);$oldGoogle=get_option('grw_google_private',false);Places::configure(['api_key'=>'TEST_FIXTURE_PHASE7_KEY_123456','terms_confirmed'=>true,'daily_budget'=>10]);GoogleBusiness::configure(['client_id'=>'phase7-fixture.apps.googleusercontent.com','client_secret'=>'TEST_FIXTURE_PHASE7_SECRET']);$private=[get_option('grw_places_private'),get_option('grw_google_private')];$settings=get_option('grw_settings');$analytics=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}grw_analytics",ARRAY_A);Installer::activate();v7($private===[get_option('grw_places_private'),get_option('grw_google_private')],'migration preserves encrypted Google credentials byte for byte');v7(get_option('grw_settings')===$settings,'migration preserves privacy and retention settings');v7($wpdb->get_results("SELECT * FROM {$wpdb->prefix}grw_analytics",ARRAY_A)===$analytics,'migration preserves historical analytics');$state=Admin::handle('state',$req);v7(!str_contains(wp_json_encode($state),'TEST_FIXTURE_PHASE7')&&!str_contains(wp_json_encode(Admin::diagnostics()),'TEST_FIXTURE_PHASE7'),'state and diagnostics expose no legacy secrets');
foreach(['grw_places_private'=>$oldPlaces,'grw_google_private'=>$oldGoogle] as $key=>$value){if($value===false)delete_option($key);else update_option($key,$value,false);}
wp_set_current_user(0);do_action('rest_api_init');$request=new WP_REST_Request('POST','/grw/v1/identify');$request->set_header('content-type','application/json');$request->set_body(wp_json_encode(['input'=>'ChIJphase7']));v7(in_array(rest_get_server()->dispatch($request)->get_status(),[401,403],true),'anonymous identifier endpoint denied');
$js=file_get_contents(dirname(__DIR__).'/assets/admin.js');foreach(['function placesForm','function googlePanel','Connect Google Account','Save private connection settings','Find Business','Retrieve live reviews','Google Cloud'] as $retired)v7(!str_contains($js,$retired),'retired setup absent: '.$retired);
v7(str_contains($js,"if(c.eligible_daily)")&&!str_contains($js,'Download All Available Reviews'),'download controls require permitted backend, no complete-archive claim');
foreach($widgets as $id)$wpdb->delete($wpdb->prefix.'grw_widgets',['id'=>$id]);foreach($ids as $id){$wpdb->delete($wpdb->prefix.'grw_reviews',['location_id'=>$id]);$wpdb->delete($wpdb->prefix.'grw_logs',['location_id'=>$id]);$wpdb->delete($wpdb->prefix.'grw_locations',['id'=>$id]);foreach(['grw_cursor_','grw_sync_counts_','grw_sync_progress_','grw_sync_error_'] as $prefix)delete_option($prefix.$id);}$grants=get_option('grw_license_grants',[]);foreach($ids as $id)unset($grants[$id]);update_option('grw_license_grants',$grants,false);remove_filter('grw_source_adapters',$filter);remove_filter('pre_http_request',$block,1);echo "$n Phase 7 assertions passed; genuine provider calls: 0\n";
