<?php
/** Offline transport fixtures. This suite does not prove live Google access. */
require rtrim(getenv('GRW_WP_ROOT'),'/').'/wp-load.php';
use Webifya\GRW\{Places,Locations,Widgets,Renderer,Sources,Sync,PermanentReviewProvider,Admin};
wp_set_current_user(1);global $wpdb;$n=0;
function v4($ok,$label){global $n;if(!$ok){throw new RuntimeException($label);}echo "PASS: $label\n";$n++;}
function p4($in){$r=new WP_REST_Request('POST');$r->set_header('content-type','application/json');$r->set_body(wp_json_encode($in));return Admin::handle('places',$r);}
$oldGrants=get_option('grw_license_grants',false);$oldPrivate=get_option('grw_places_private',false);$oldBudget=get_option('grw_places_budget',false);delete_option('grw_places_private');delete_option('grw_places_budget');
v4(!Places::status()['configured'],'fresh Places disconnected');
v4(is_wp_error(Places::details('ChIJfixture')),'key required');
v4(Places::id('ChIJfixture')==='ChIJfixture','Place ID parsing');
v4(Places::id('https://www.google.com/maps/search/?api=1&query=x&query_place_id=ChIJfixture')==='ChIJfixture','URL Place ID parsing');
v4(Places::id('https://attacker.invalid/?place_id=ChIJfixture')==='','foreign host rejected');
v4(Places::id('https://127.0.0.1/?place_id=ChIJfixture')==='','private address rejected');
v4(Places::id('https://maps.app.goo.gl/example')==='','share URL is not invented into Place ID');
v4(Places::id('https://www.google.com/maps?place_id[]=ChIJfixture')==='','nested URL Place ID rejected');
v4(is_wp_error(p4(['action'=>'configure','api_key'=>str_repeat('a',39)])),'policy confirmation required');
v4(is_wp_error(p4(['action'=>'configure','api_key'=>'bad','terms_confirmed'=>true])),'malformed key rejected');
$configure=['action'=>'configure','api_key'=>'TEST_FIXTURE_'.str_repeat('x',30),'terms_confirmed'=>true,'daily_budget'=>100];
v4(p4($configure)['configured'],'fixture key encrypted configuration');
v4(!str_contains(get_option('grw_places_private'),$configure['api_key']),'key absent from encrypted option plaintext');
v4(!str_contains(wp_json_encode(Places::status()),$configure['api_key']),'status never exposes key');
v4(Places::status()['maximum']===5,'accurate five review capability');
v4(Sources::capabilities('google_places')['storage']==='request_only','Places no stored reviews policy');
v4(!Sources::capabilities('google_business')['public_display'],'owner dashboard separate from public review provider');
v4(Sources::capabilities('manual')['storage']==='legacy','legacy testimonial provenance');
v4(is_wp_error(Locations::save(['name'=>'Missing Place ID','provider'=>'google_places'])),'connection requires Place ID');
$loc=Locations::save(['name'=>'SYNTHETIC Places fixture','place_id'=>'ChIJfixture','provider'=>'google_places','active'=>true]);
v4(Locations::get($loc)['next_sync']==0,'Places does not schedule prohibited prefetch');
v4(is_wp_error(Sync::run($loc)),'Places rejected from stored synchronization');
v4(!Sources::connection(Locations::get($loc))['connected'],'saved key and ID are not connected proof');
$payload=['id'=>'ChIJfixture','displayName'=>['text'=>'SYNTHETIC fixture business'],'formattedAddress'=>'Fixture address','googleMapsUri'=>'https://www.google.com/maps?cid=123','rating'=>4.8,'userRatingCount'=>100,'attributions'=>[['provider'=>'Fixture attribution','providerUri'=>'https://example.org/credits']],'reviews'=>[]];
for($i=0;$i<5;$i++){$payload['reviews'][]=['name'=>'places/ChIJfixture/reviews/fixture'.$i,'authorAttribution'=>['displayName'=>'SYNTHETIC reviewer '.$i,'photoUri'=>'https://example.org/avatar.png','uri'=>'https://www.google.com/maps/contrib/123'],'rating'=>5,'originalText'=>['text'=>'SYNTHETIC <b>original</b> review বাংলা '.$i],'text'=>['text'=>'Translated text'],'publishTime'=>'2024-01-01T10:00:00Z','googleMapsUri'=>'https://www.google.com/maps/reviews/data=fixture'.$i,'visitDate'=>['year'=>2024,'month'=>1]];}
$mode=200;$calls=0;$http=function($pre,$args,$url)use(&$payload,&$mode,&$calls,$configure){if(!str_starts_with($url,'https://places.googleapis.com/v1/places/'))return $pre;$calls++;v4(!str_contains($url,$configure['api_key']),'key never in request URL');v4(($args['headers']['X-Goog-Api-Key']??'')===$configure['api_key'],'private header credential');v4($args['redirection']===0&&$args['reject_unsafe_urls'],'fixed endpoint, redirects disabled, SSRF guard');v4(!str_contains($args['headers']['X-Goog-FieldMask'],'*'),'explicit field mask');return ['headers'=>[],'response'=>['code'=>$mode],'body'=>wp_json_encode($payload),'cookies'=>[]];};add_filter('pre_http_request',$http,10,3);
$before=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}grw_reviews");$r=Places::retrieve($loc);
v4(count($r['reviews'])===5,'five review transport fixture');v4($r['reviews'][0]['content']===$payload['reviews'][0]['originalText']['text'],'authentic original text preserved unmodified in memory');v4($r['reviews'][0]['author_url']==='https://www.google.com/maps/contrib/123','author link preserved');v4($r['reviews'][0]['visit_date']==='2024-01','visit month for France retained');v4($r['reviews'][0]['permalink']===$payload['reviews'][0]['googleMapsUri'],'original review URI preserved');v4(Sources::connection(Locations::get($loc))['connected'],'connected only after actual review-bearing fixture response');v4((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}grw_reviews")===$before,'Places content never imported into database');v4(!str_contains(wp_json_encode(get_option('grw_places_validation_'.$loc)),'SYNTHETIC'),'validation stores no review content or identity');
$w=Widgets::save(['name'=>'SYNTHETIC live widget','config'=>['locations'=>[$loc],'show_avatar'=>false,'show_name'=>false,'show_date'=>false,'show_map'=>true,'show_maps'=>true,'template'=>'classic','minimum'=>4]]);
$placeholder=Renderer::render($w);v4(str_contains($placeholder,'data-grw-live'),'page cache contains placeholder only');v4(!str_contains($placeholder,'SYNTHETIC reviewer')&&!str_contains($placeholder,'iframe'),'page contains no cached reviews or replacement maps');v4(!str_contains($placeholder,$configure['api_key']),'no frontend credential exposure');
$preview=Renderer::render($w,[],true);v4(str_contains($preview,'Google Maps')&&str_contains($preview,'Fixture attribution'),'mandatory Google and third-party attribution');v4(str_contains($preview,'maps/contrib/123'),'author profile link visible even name disabled');v4(str_contains($preview,'grw-avatar')&&str_contains($preview,'grw-date'),'attribution visibility cannot be suppressed');v4(str_contains($preview,'Visited: 2024-01'),'visit date displayed');v4(str_contains($preview,'Display order: latest; minimum rating: 4'),'selection and ordering explained');v4(str_contains($preview,'&lt;b&gt;original&lt;/b&gt;')&&!str_contains($preview,'<b>original</b>'),'provider text escaped on display');v4(!str_contains($preview,'<iframe'),'Places never substitutes map');
$request=new WP_REST_Request('POST');$request->set_param('id',$w);$request->set_param('token','invalid');v4(is_wp_error(Places::public_widget($request)),'unsigned arbitrary public fetch denied');$request->set_param('token',Places::token($w));wp_set_current_user(0);$response=Places::public_widget($request);v4(str_contains($response->get_data()['html'],'SYNTHETIC reviewer'),'signed public widget ephemeral rendering');v4(str_contains($response->get_headers()['Cache-Control'],'no-store'),'content response disables caching');wp_set_current_user(1);$request->set_param('admin_preview',true);$request->set_param('token',Places::token($w,true));$adminResponse=Places::public_widget($request);v4(str_contains($adminResponse->get_data()['html'],'&quot;track&quot;:false'),'signed admin live preview excludes tracking even without REST cookie nonce');$request->set_param('admin_preview',false);v4(is_wp_error(Places::public_widget($request)),'cannot change signed tracking context');$request->set_param('token',Places::token($w));v4($calls===1,'same request memory reuse avoids duplicate provider charges');
// Configuration reset starts a fresh request state for each transport error fixture.
Places::configure($configure);$mode=403;v4(is_wp_error(Places::retrieve($loc)),'authentication fixture error');v4(!Sources::connection(Locations::get($loc))['connected'],'failed validation clears connected state');
Places::configure($configure);$mode=429;$err=Places::retrieve($loc);v4(is_wp_error($err)&&$err->get_error_code()==='places_quota','rate limit reported clearly');
Places::configure($configure);$mode=200;$payload['id']='wrong';v4(is_wp_error(Places::retrieve($loc)),'wrong business identity rejected');$payload['id']='ChIJfixture';
Places::configure($configure);$payload['consumerAlert']=['test'=>true];v4(is_wp_error(Places::retrieve($loc)),'consumer alert requires direct listing review');unset($payload['consumerAlert']);
Places::configure($configure);$payload['reviews']=[];v4(Places::retrieve($loc)['reviews']===[]&&!Sources::connection(Locations::get($loc))['connected'],'zero reviews is not advertised as connected collection');v4(Renderer::render($w,[],true)!==''&&str_contains(Renderer::render($w,[],true),'No reviews connected yet'),'clean empty admin preview');v4(Renderer::render($w,[],false,true)==='','public empty hide option');v4(str_contains(Renderer::render($w,['empty_mode'=>'message','empty_message'=>'No customer reviews yet.'],false,true),'No customer reviews yet.'),'custom public empty message');
Places::configure($configure);update_option('grw_places_budget',gmdate('Y-m-d').':100');$beforeCalls=$calls;$err=Places::details('ChIJfixture');v4(is_wp_error($err)&&$err->get_error_code()==='places_budget'&&$calls===$beforeCalls,'site request budget prevents further billable calls');
class LicensedFixture4 implements PermanentReviewProvider{public function label():string{return 'SYNTHETIC permitted provider';}public function supports_sync():bool{return true;}public function policy():array{return ['permanent_storage'=>true,'public_display'=>true,'license_reference'=>'https://example.org/fixture-license','maximum'=>100,'history'=>true,'new_reviews'=>true];}public function fetch(array $location,?string $cursor){return ['reviews'=>[['external_id'=>'fixture-stable','reviewer'=>'SYNTHETIC licensed reviewer','content'=>get_option('grw_fixture4_text','Fixture <em>literal</em> content'),'rating'=>5,'source_name'=>'Synthetic permitted feed','review_date'=>'2024-01-01']],'cursor'=>null];}}
$provider=function($a){$a['fixture4']=new LicensedFixture4();return $a;};add_filter('grw_source_adapters',$provider);
$daily=Locations::save(['name'=>'SYNTHETIC daily provider','provider'=>'fixture4','active'=>true]);v4(Locations::get($daily)['next_sync']>=time()+86390,'daily schedule defaults to 24 hours');v4(Sources::connection(Locations::get($daily))['eligible_daily'],'licensed fixture capability registered');
Webifya\GRW\Reviews::import([['external_id'=>'legacy-retained','reviewer'=>'SYNTHETIC legacy record','content'=>'Legacy record retained, never authenticated as provider retrieval','rating'=>1]],$daily);
v4(!Sources::connection(Locations::get($daily))['connected'],'legacy records cannot validate a licensed collection');
$r=Sync::run($daily);v4($r['added']===1&&Sources::connection(Locations::get($daily))['connected'],'manual licensed fixture sync validates real row flow');v4($wpdb->get_var($wpdb->prepare("SELECT content FROM {$wpdb->prefix}grw_reviews WHERE location_id=%d AND source_type='licensed'",$daily))==='Fixture <em>literal</em> content','licensed original review text preserved unmodified');
v4(get_option('grw_license_grants')[$daily]['fixture4']['reference']==='https://example.org/fixture-license','review permission reference retained');
v4(Sources::connection(Locations::get($daily))['last_counts']['added']===1,'last sync statistics saved');v4(Locations::get($daily)['next_sync']>=time()+86390,'successful fixture sync schedules next 24 hours');
$r=Sync::run($daily);v4($r['added']===0&&$r['unchanged']===1,'stable IDs deduplicate recurring sync');update_option('grw_fixture4_text','Changed fixture content');$r=Sync::run($daily);v4($r['updated']===1,'changed licensed content updates');delete_option('grw_fixture4_text');
$wpdb->update($wpdb->prefix.'grw_locations',['next_sync'=>time()-1],['id'=>$daily]);Sync::tick();v4(Locations::get($daily)['next_sync']>time()+86000,'actual scheduler tick processes due licensed fixture');
$new=Widgets::save(['name'=>'SYNTHETIC connected widget','config'=>['locations'=>[$daily]]]);v4(str_contains(Renderer::render($new),'SYNTHETIC licensed reviewer')&&!str_contains(Renderer::render($new),'SYNTHETIC legacy record'),'connected default displays retrieved licensed rows only');
$r=new WP_REST_Request('GET');$s=Admin::handle('state',$r);v4(count(array_filter($s['connected_reviews'],fn($row)=>(int)$row['location_id']===$daily))===1,'connected review dashboard excludes retained legacy rows');v4(Widgets::defaults()['source']==='connected','new widgets default to authentic connected providers');
$legacy=Locations::save(['name'=>'SYNTHETIC legacy-only','provider'=>'manual']);$empty=Widgets::save(['name'=>'SYNTHETIC no connected reviews','config'=>['locations'=>[$legacy]]]);v4(Renderer::render($empty)==='','new widget cannot implicitly publish legacy testimonials');
$searchMock=function($pre,$args,$url){if($url!=='https://places.googleapis.com/v1/places:searchText')return $pre;v4($args['redirection']===0&&$args['reject_unsafe_urls'],'business search uses fixed safe endpoint');$body=json_decode($args['body'],true);v4($body['textQuery']==='SYNTHETIC Business'&&$body['pageSize']===3,'Maps URL name searched through official API with bounded candidates');return ['response'=>['code'=>200],'headers'=>[],'body'=>wp_json_encode(['places'=>[['id'=>'ChIJcandidate','displayName'=>['text'=>'SYNTHETIC search candidate']]]]),'cookies'=>[]];};add_filter('pre_http_request',$searchMock,11,3);update_option('grw_places_budget',gmdate('Y-m-d').':0');$search=Places::lookup('https://www.google.com/maps/place/SYNTHETIC+Business/@1,2,3z');v4($search['candidates'][0]['id']==='ChIJcandidate','standard Maps business URL returns candidates for confirmation');remove_filter('pre_http_request',$searchMock,11);
Places::configure(['action'=>'disconnect']);v4(!Places::status()['configured'],'credential disconnect');v4(!Sources::connection(Locations::get($loc))['connected'],'disconnected key cannot retain connected status');$request->set_param('token',Places::token($w).'old');v4(is_wp_error(Places::public_widget($request)),'key rotation invalidates public fetch token');
remove_filter('pre_http_request',$http,10);remove_filter('grw_source_adapters',$provider);
foreach([$w,$new,$empty] as $id)$wpdb->delete($wpdb->prefix.'grw_widgets',['id'=>$id]);foreach([$loc,$daily,$legacy] as $id){$wpdb->delete($wpdb->prefix.'grw_reviews',['location_id'=>$id]);$wpdb->delete($wpdb->prefix.'grw_logs',['location_id'=>$id]);$wpdb->delete($wpdb->prefix.'grw_locations',['id'=>$id]);delete_option('grw_places_validation_'.$id);delete_option('grw_sync_counts_'.$id);}
if($oldGrants!==false)update_option('grw_license_grants',$oldGrants,false);else delete_option('grw_license_grants');
if($oldPrivate!==false)update_option('grw_places_private',$oldPrivate,false);if($oldBudget!==false)update_option('grw_places_budget',$oldBudget,false);else delete_option('grw_places_budget');
echo "$n Phase 4 fixture assertions passed; live Google integration NOT tested.\n";
